#!/bin/bash
random_num=$((RANDOM % 15 + 1))
num=0

while [ "$random_num" -ne "$num" ]; do
    read -p "Угадай число в диапазоне (1-15): " num
    
    if [ "$num" -eq "$random_num" ]; then
        echo "Угадал!Молодец!"
        break
    else
        if [ "$num" -gt "$random_num" ]; then
            echo "Меньше"
        else
            echo "Больше"
        fi
    fi
done
